
spring:
  application:
    name: microservice-discovery-eureka-ha
  profiles:
    activate:
      peer1
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8086/eureka/,http://peer1:8085/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 1000
    #    renewal-threshold-update-interval-ms: 2000
    expected-client-renewal-interval-seconds: 15
    wait-time-in-ms-when-sync-empty: 60000
---
server:
  port: 8085
eureka:
  instance:
    hostname: peer1
spring:
 profiles:  peer1
---
server:
  port: 8086
eureka:
  instance:
    hostname: peer2
spring:
  profiles: peer2


