server:
  port: 8082

eureka:
  instance:
    hostname: localhost

  client:

    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 1000
#    renewal-threshold-update-interval-ms: 2000
    expected-client-renewal-interval-seconds: 15
    wait-time-in-ms-when-sync-empty: 60000





