server:
  port: 8080




bookService:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8083
    MaxAutoRetries: 3
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxAutoRetriesNextServer: 0
    retryableStatusCodes: 503, 408,
    OkToRetryOnAllOperations: true
#    http:
#      client:
#        enabled: true