
server:
  port: 8084






spring:
  application:
    name: consumerServer




#配置组件暴露细节
management:
  endpoint:
    health:
      show-details: always
      show-components: always

#暴露actuator/hystrix.stream路径
  endpoints:
    web:
      exposure:
        include: [health, hystrix.stream]

# 添加localhost到代理流list
#  让dashboard可以接收http://localhost:8081/actuator/hystrix.stream的数据
hystrix:
  dashboard:
    proxy-stream-allow-list: localhost

